# Generated by Django 3.1.3 on 2020-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20201130_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
