# Generated by Django 3.1.3 on 2020-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20201209_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendedquestion',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.option'),
        ),
    ]
